name: Publish website

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy through FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://ftp.as-mi.ro/
        ftp-username: zilele
        ftp-password: ${{ secrets.FTP_PASSWORD }}
